apiVersion: v1
kind: Service
metadata:
  name: bobinator
  namespace: bobinator
spec:
  type: LoadBalancer
  loadBalancerIP: 10.20.30.44
  selector:
    app: bobinator
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
